"""Add email verification field

Revision ID: 3ed125c44d00
Revises: 2d7a23b170a8
Create Date: 2026-01-21 11:16:16.583791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3ed125c44d00'
down_revision: Union[str, Sequence[str], None] = '2d7a23b170a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
