"""Create product table

Revision ID: 71abfa4365dc
Revises: 3ed125c44d00
Create Date: 2026-01-22 15:46:00.645418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '71abfa4365dc'
down_revision: Union[str, Sequence[str], None] = '3ed125c44d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.Enum('headphones', 'speakers', 'earphones', name='categoryenum'), nullable=False),
    sa.Column('category_image', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('features', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('includes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('gallery', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('others', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_slug'), 'product', ['slug'], unique=True)
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_index(op.f('ix_product_slug'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
