"""Change product schema to match challenges data format

Revision ID: 8ff1004c5bf6
Revises: 71abfa4365dc
Create Date: 2026-01-23 15:26:31.444853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8ff1004c5bf6'
down_revision: Union[str, Sequence[str], None] = '71abfa4365dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('categoryImage', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('product', sa.Column('new', sa.Boolean(), nullable=False))
    op.drop_column('product', 'category_image')
    op.drop_column('product', 'is_new')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_new', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('category_image', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('product', 'new')
    op.drop_column('product', 'categoryImage')
    # ### end Alembic commands ###
